accounts/urls.py
from django.urls import path
from accounts import views 
from django.contrib.auth import views as auth_views

app_name = 'accounts'

auth_views.PasswordResetView
urlpatterns = [
    # login, logout, registeration/signup
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestBlogsFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path("rss/feed/", LatestBlogsFeed()),
]

fsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'static':StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserCreationWithEmailForm(UserCreationForm):
    
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        email = self.clean_email()
        user.email = email
        
        if commit:
            user.save()
        return user
    
    def clean_email(self):
        """Reject usernames that differ only in case."""
        email = self.cleaned_data.get("email")
        if (
            email
            and self._meta.model.objects.filter(email__iexact=email).exists()
        ):
            self._update_errors(
                ValidationError(
                    {
                        "email": self.instance.unique_error_message(
                            self._meta.model, ["email"]
                        )
                    }
                )
            )
        else:
            return email    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from accounts.forms import UserCreationWithEmailForm

# Create your views here.


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    
    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            # if username field is actually username
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('/')
                            
        else:
            # maybe username is email
            email = form.cleaned_data['username']
            user_obj = get_user_by_email(email)
            if user_obj:
                password = form.cleaned_data['password']
                user = authenticate(username=user_obj, password=password)
                if user:
                    login(request, user)
                    return redirect('/')
            
    if request.method == "POST":
        # at least one of the email, username, password fields were incorrect 
        messages.add_message(request, messages.ERROR, 'Invalid Credentials')
        
    form = AuthenticationForm()
    context = {'form':form}
    return render(request, 'accounts/login.html', context)
    

def get_user_by_email(email):
    user = User.objects.filter(email = email).first()
    return user
    
@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        form = UserCreationWithEmailForm()
        if request.method == "POST":
            form = UserCreationWithEmailForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect(reverse('accounts:login')) 

        context = {'form':form}
        return render(request, 'accounts/signup.html', context)
    
    else:
        return redirect('/')

templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">

    <form class="form-signin" method="POST" action="{% url 'accounts:login' %}"> {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">sign in</h1>
      
      <label class="sr-only">Email or Username</label>
      <input name="username" type="text" class="form-control" placeholder="Email or Username" required autofocus>
      <label class="sr-only">Password</label>
      <input name="password" type="password" class="form-control" placeholder="Password" required>

      <div class="checkbox mb-3">
        <a href="{% url 'accounts:password_reset' %}" class="a">Forgot Passowrd</a>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      {% for message in messages %}
      <div class="alert-danger" role="alert">{{ message }}</div>
      {% endfor %}
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>

    </form>



  </body>
</html>

templates/accounts/password-reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/password-reset.css' %}">

</head>
<body>
    <div class="card text-center centere">
        <div class="card-header h5 text-white bg-primary">Password Reset</div>
        <div class="card-body px-5">
            <p class="card-text py-2">
                Enter your email address and we'll send you an email with instructions to reset your password.
            </p>
            <form method="POST" action="{% url 'accounts:password_reset' %}" data-mdb-input-init class="form-outline"> {% csrf_token %}
                <input type="email" name="email" class="form-control my-3" placeholder="Email">
                <button type='submit' data-mdb-ripple-init class="btn btn-primary w-100">Reset password</button>
            </form>
            
            <div class="d-flex justify-content-between mt-4">
                <a href="{% url 'accounts:login' %}">Login</a>
                <a href="{% url 'accounts:signup' %}">Signup</a>
            </div>
        </div>
    </div>
</body>
</html>

templates/accounts/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sign Up</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="POST" action="{% url 'accounts:signup' %}"> {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">sign up</h1>

        {% comment %} {{form.as_p}} {% endcomment %}
        <label class="sr-only">Username</label> 
        <input name="username" type="text" class="form-control" placeholder="Username" required autofocus>  
        <label class="sr-only">Email</label> 
        <input name="email" type="email" class="form-control" placeholder="Email" required autofocus>  
        <label class="sr-only">Password</label> 
        <input name="password1" type="password" class="form-control" placeholder="Password" required> 
        <label class="sr-only">Confirm Password</label> 
        <input name="password2" type="password" class="form-control" placeholder="Password Confirm" required>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}
      {% endfor %}
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>